<?php
/**
 * @file
 * Code for the OS2Web indholdstyper feature.
 */

include_once('os2web_base.features.inc');

/**
 * Implements hook_date_format_types().
 */
function os2web_base_date_format_types() {
  // Define the core date format types.
  return array(
    'os2web_base_date_only' => t('Date Only'),
  );
}
/**
 * Implements hook_date_formats().
 */
function os2web_base_date_formats() {
  return array(
    array(
      'type' => 'os2web_base_date_only',
      'format' => 'Y-m-d',
      'locales' => array(),
    ),
  );
}
